[project]
name = "adp-chat-client"
version = "0.1.0"
description = "backend for the adp-chat-client"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "aioboto3==15.0.0",
    "aiohttp==3.14.3",
    "asyncpg==0.30.0",
    "greenlet==3.2.3",
    "pyjwt==2.13.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.0",
    "pytz==2025.2",
    "pyyaml==6.0.2",
    "pydantic==2.11.7",
    "pydantic-settings==2.9.1",
    "sanic==25.3.0",
    "sanic-ext==24.12.0",
    "sanic-restful-api==0.2.1",
    "sanic-routing==23.12.0",
    "sqlalchemy==2.0.41",
    "termcolor==3.1.0",
    "ujson==5.13.0",
    "cryptography==50.0.0",
    "orjson==3.11.9",
    "urllib3==2.7.0",
    "limits>=5.6.0",
    "jwcrypto>=1.5.6",
    "cos-python-sdk-v5>=1.9.30",
    "pydash>=8.0.0",
    "redis==6.2.0",
    "e2b-code-interpreter==2.9.0",
    "tencentcloud-sdk-python-ags==3.1.149",
]
[project.optional-dependencies]
dev = [
    "pytest==8.4.0",
    "pytest-asyncio==1.0.0",
    "sanic-testing==24.6.0",
]
